In [1]:
# Create a python list

a = ["0", 1, "two", "3", 4]

In [2]:
# Print each element
print("a[0]:", a[0])
print("a[1]:", a[1])
print("a[2]:", a[2])
print("a[3]:", a[3])
print("a[4]:", a[4])


a[0]: 0
a[1]: 1
a[2]: two
a[3]: 3
a[4]: 4


In [3]:
# import numpy library

import numpy as np 

In [4]:
# Create a numpy array

a = np.array([0, 1, 2, 3, 4])
a

array([0, 1, 2, 3, 4])

In [5]:
# Print each element

print("a[0]:", a[0])
print("a[1]:", a[1])
print("a[2]:", a[2])
print("a[3]:", a[3])
print("a[4]:", a[4])

a[0]: 0
a[1]: 1
a[2]: 2
a[3]: 3
a[4]: 4


In [6]:
print(np.__version__)

1.20.1


In [7]:
# Check the type of the array

type(a)

numpy.ndarray

In [8]:
# Check the type of the values stored in numpy array

a.dtype

dtype('int32')

In [9]:
# Create numpy array

c = np.array([20, 1, 2, 3, 4])
c

array([20,  1,  2,  3,  4])

In [10]:
# Assign the first element to 100

c[0] = 100
c

array([100,   1,   2,   3,   4])

In [11]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])

[2 4]


In [12]:
# Create the index list

select = [0, 2, 3, 4]
select

[0, 2, 3, 4]

In [13]:
d = c[select]
d

array([100,   2,   3,   4])

In [14]:
# Assign the specified elements to new value

c[select] = 100000
c

array([100000,      1, 100000, 100000, 100000])

In [15]:
# Create a numpy array

a = np.array([0, 1, 2, 3, 4])
a

array([0, 1, 2, 3, 4])

In [16]:
# Get the size of numpy array

a.size

5

In [17]:
# Get the number of dimensions of numpy array

a.ndim

1

In [18]:
# Get the shape/size of numpy array

a.shape

(5,)

In [19]:
# Plotting functions


import time 
import sys
import numpy as np 

import matplotlib.pyplot as plt
%matplotlib inline  

def Plotvec1(u, z, v):
    
    ax = plt.axes() # to generate the full window axes
    ax.arrow(0, 0, *u, head_width=0.05, color='r', head_length=0.1)# Add an arrow to the  U Axes with arrow head width 0.05, color red and arrow head length 0.1
    plt.text(*(u + 0.1), 'u')#Adds the text u to the Axes 
    
    ax.arrow(0, 0, *v, head_width=0.05, color='b', head_length=0.1)# Add an arrow to the  v Axes with arrow head width 0.05, color red and arrow head length 0.1
    plt.text(*(v + 0.1), 'v')#Adds the text v to the Axes 
    
    ax.arrow(0, 0, *z, head_width=0.05, head_length=0.1)
    plt.text(*(z + 0.1), 'z')#Adds the text z to the Axes 
    plt.ylim(-2, 2)#set the ylim to bottom(-2), top(2)
    plt.xlim(-2, 2)#set the xlim to left(-2), right(2)

  


In [20]:
# Plot numpy arrays

Plotvec1(u, z, v)

NameError: name 'u' is not defined

In [21]:
# Import the libraries

import numpy as np 
import matplotlib.pyplot as plt

In [22]:
# Create a list

a = [[11, 12, 13], [21, 22, 23], [31, 32, 33]]
a

[[11, 12, 13], [21, 22, 23], [31, 32, 33]]

In [23]:
# Convert list to Numpy Array
# Every element is the same type

A = np.array(a)
A

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [24]:
# Show the numpy array dimensions

A.ndim

2

In [25]:
# Show the numpy array shape

A.shape

(3, 3)

In [26]:
# Show the numpy array size

A.size

9

In [27]:
# Access the element on the second row and third column

A[1, 2]

23

In [28]:
# Access the element on the second row and third column

A[1][2]

23

In [29]:
# Access the element on the first row and first column

A[0][0]

11

In [30]:
# Access the element on the first row and first and second columns

A[0][0:2]

array([11, 12])

In [31]:
# Access the element on the first and second rows and third column

A[0:2, 2]

array([13, 23])

In [32]:
# Create a numpy array X

X = np.array([[1, 0], [0, 1]]) 
X

array([[1, 0],
       [0, 1]])

In [33]:
# Create a numpy array Y

Y = np.array([[2, 1], [1, 2]]) 
Y

array([[2, 1],
       [1, 2]])

In [34]:
# Add X and Y

Z = X + Y
Z

array([[3, 1],
       [1, 3]])

In [35]:
# Create a numpy array Y

Y = np.array([[2, 1], [1, 2]]) 
Y

array([[2, 1],
       [1, 2]])

In [36]:
# Multiply Y with 2

Z = 2 * Y
Z

array([[4, 2],
       [2, 4]])